In [1]:
!pip install pulp #Python Linear Programming
import pulp
!apt-get install -y -qq glpk-utils
from pulp import GLPK
import pandas as pd
import numpy as np

from google.colab import drive
import os
drive.mount('/content/drive')
os.chdir("/content/drive/My Drive/Colab Notebooks/Modelling")

df = pd.read_csv("Modelling data.csv")


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.3/14.3 MB 71.6 MB/s eta 0:00:00
Selecting previously unselected package libsuitesparseconfig5:amd64.
(Reading database ... 120882 files and directories currently installed.)
Preparing to unpack .../libsuitesparseconfig5_1%3a5.10.1+dfsg-4build1_amd64.deb ...
Unpacking libsuitesparseconfig5:amd64 (1:5.10.1+dfsg-4build1) ...
Selecting previously unselected package libamd2:amd64.
Preparing to unpack .../libamd2_1%3a5.10.1+dfsg-4build1_amd64.deb ...
Unpacking libamd2:amd64 (1:5.10.1+dfsg-4build1) ...
Selecting previously unselected package libcolamd2:amd64.
Preparing to unpack .../libcolamd2_1%3a5.10.1+dfsg-4build1_amd64.deb ...
Unpacking libcolamd2:amd64 (1:5.10.1+dfsg-4build1) ...
Selecting previously unselected package libglpk40:amd64.
Preparing to unpack .../libglpk40_5.0-1_amd64.deb ...
Unpacking libglpk40:amd64 (5.0-1) ...
Selecting previously unselected package glpk-utils.
Preparing to unpack .../glpk-utils_5.0-1_amd64.deb ...
Unpackin

In [2]:
weights_matrix = np.empty((9,9))
for i in range(9):
    model = pulp.LpProblem("Investment Analysis", pulp.LpMaximize) # Create an LP maximization problem
    m1 = pulp.LpVariable("m1", lowBound=0, upBound=None, cat='Continuous') # Create a variable m1>=0
    m2 = pulp.LpVariable("m2", lowBound=0, upBound=None, cat='Continuous') # Create a variable m2>=0
    n1 = pulp.LpVariable("n1", lowBound=0, upBound=None, cat='Continuous') # Create a variable n1>=0
    n2 = pulp.LpVariable("n2", lowBound=0, upBound=None, cat='Continuous') # Create a variable n2>=0



    model += m1*df["Y1"][i] + m2*df["Y2"][i]  #objective function

    model += n1*df["X1"][i] + n2*df["X4"][i] == 1 #first constraint (equality)

    for j in range(9):
        model += m1*df["Y1"][j] + m2*df["Y2"][j] - n1*df["X1"][j] - n2*df["X4"][j] <= 0

    status = model.solve(GLPK(msg=True, options=['--ranges', 'sensitivity.txt']))
    print("Model Status:{}".format(pulp.LpStatus[model.status]))

    list_weights=[]
    for k in model.variables():
	      print(k.name, "=", k.varValue, "\tReduced Cost =", k.dj)
    for k in model.variables():
        list_weights=list_weights+[k.varValue]
    for l in range(4):
        value= list_weights[l]
        weights_matrix[l,i] = value

    print("Objective=", pulp.value(model.objective))

    # Displaying Shadow Price & Slack Value per Constraint
    print ("\nSensitivity Analysis\nConstraint\t\tShadow Price\tSlack")
    for name, m in model.constraints.items():
	      print(name, ":", m, "\t", m.pi, "\t\t", m.slack)

/usr/local/lib/python3.10/dist-packages/pulp/pulp.py:1352: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")


Model Status:Optimal
m1 = 0.0 	Reduced Cost = None
m2 = 2.61 	Reduced Cost = None
n1 = 0.0 	Reduced Cost = None
n2 = 6.0024e-05 	Reduced Cost = None
Objective= 0.9999999988199999

Sensitivity Analysis
Constraint		Shadow Price	Slack
_C1 : 114.8*n1 + 16660*n2 = 1.0 	 None 		 None
_C2 : 8.71*m1 + 0.383141762*m2 - 114.8*n1 - 16660*n2 <= -0.0 	 None 		 None
_C3 : 8.1*m1 + 0.01618123*m2 - 106.8*n1 - 12376*n2 <= -0.0 	 None 		 None
_C4 : 6.2*m1 + 0.041407867*m2 - 84.6*n1 - 24463*n2 <= -0.0 	 None 		 None
_C5 : 3.12*m1 + 0.031152648*m2 - 77.7*n1 - 6810*n2 <= -0.0 	 None 		 None
_C6 : 0.12*m1 + 0.071428571*m2 - 56.3*n1 - 42442*n2 <= -0.0 	 None 		 None
_C7 : 1.32*m1 + 0.043956044*m2 - 45.8*n1 - 9639*n2 <= -0.0 	 None 		 None
_C8 : 3.07*m1 + 0.1953125*m2 - 37.8*n1 - 17515*n2 <= -0.0 	 None 		 None
_C9 : 6.28*m1 + 0.0253614*m2 - 36.7*n1 - 7872*n2 <= -0.0 	 None 		 None
_C10 : 1.88*m1 + 0.031786395*m2 - 29.7*n1 - 7237*n2 <= -0.0 	 None 		 None
Model Status:Optimal
m1 = 0.101285 	Reduced Cost = Non

In [3]:
efficiency_table =np.empty((9,9))
average_list =[]
for row in range(9):
    row_values=[]
    for column in range(9):
      value = ((weights_matrix[0,column]*df["Y1"][row])+(weights_matrix[1,column]*df["Y2"][row]))/((weights_matrix[2,column]*df["X1"][row])+(weights_matrix[3,column]*df["X4"][row]))

      efficiency_table[row,column]=value
      row_values=row_values+[value]
    from statistics import mean
    average =mean(row_values)
    average_list =average_list+[average]

In [4]:
average_list_rounded = [ '%.2f' % elem for elem in average_list ]

In [5]:
country_list = ['Brazil','Vietnam','Chile','India','Kazakhstan','Egypt','Mexico','Indonesia','Morocco' ]


In [6]:
for country in country_list:
    index = country_list.index(country)
    print("Cross-efficiency score for",country,"=",average_list_rounded[index])

Cross-efficiency score for Brazil = 0.86
Cross-efficiency score for Vietnam = 0.44
Cross-efficiency score for Chile = 0.28
Cross-efficiency score for India = 0.34
Cross-efficiency score for Kazakhstan = 0.11
Cross-efficiency score for Egypt = 0.23
Cross-efficiency score for Mexico = 0.70
Cross-efficiency score for Indonesia = 0.72
Cross-efficiency score for Morocco = 0.35


In [7]:
display(efficiency_table)
np.set_printoptions(suppress=True, precision = 2)
print(efficiency_table)
np.savetxt('table.txt', efficiency_table, fmt='%f')

array([[1.00000016, 0.65534249, 0.77247371, 0.9999976 , 0.64591973,
        0.99999838, 0.99999786, 0.65534179, 0.99999788],
       [0.05685214, 0.82040801, 0.42641767, 0.79836587, 0.02932252,
        0.46466075, 0.04780434, 0.82040712, 0.46466045],
       [0.07360185, 0.31769263, 0.44928869, 0.32873403, 0.09472693,
        0.42712566, 0.11750069, 0.31769229, 0.42712535],
       [0.19891312, 0.57429185, 0.26058491, 0.61924624, 0.07759521,
        0.31310565, 0.1333318 , 0.57429123, 0.31310548],
       [0.07317988, 0.00354414, 0.14926681, 0.03112723, 0.24554128,
        0.13899879, 0.18556484, 0.00354413, 0.1389987 ],
       [0.19829063, 0.17165922, 0.25999154, 0.2377835 , 0.18574369,
        0.30504375, 0.25847419, 0.17165903, 0.30504358],
       [0.48488134, 0.21971181, 1.00000388, 0.39204156, 0.99999813,
        0.99999882, 0.99999859, 0.21971158, 0.99999815],
       [0.1400889 , 0.99999938, 1.00000232, 0.99999726, 0.13374209,
        0.99999866, 0.18495449, 0.9999983 , 0.99999796],


[[1.   0.66 0.77 1.   0.65 1.   1.   0.66 1.  ]
 [0.06 0.82 0.43 0.8  0.03 0.46 0.05 0.82 0.46]
 [0.07 0.32 0.45 0.33 0.09 0.43 0.12 0.32 0.43]
 [0.2  0.57 0.26 0.62 0.08 0.31 0.13 0.57 0.31]
 [0.07 0.   0.15 0.03 0.25 0.14 0.19 0.   0.14]
 [0.2  0.17 0.26 0.24 0.19 0.31 0.26 0.17 0.31]
 [0.48 0.22 1.   0.39 1.   1.   1.   0.22 1.  ]
 [0.14 1.   1.   1.   0.13 1.   0.18 1.   1.  ]
 [0.19 0.33 0.46 0.38 0.21 0.49 0.27 0.33 0.49]]
